name: Docker

on:
  push:
    branches: [ main ]
    tags: [ ]

env:
  REPO_NAME: skymatic
  IMAGE_NAME: apache-php-base

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)

  push:
    needs: build # Ensure build job passes before pushing image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build . --file Dockerfile --tag image
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=$REPO_NAME/$IMAGE_NAME
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [ "$VERSION" == "main" ] && VERSION=latest

          echo VERSION=$VERSION

          docker tag image $REPO_NAME/$IMAGE_NAME:$VERSION
          docker push $REPO_NAME/$IMAGE_NAME:$VERSION
