name: Docker

on:
  push:
    branches: [ master ]
    tags: [ ]

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: skymatic/apache-php-base
          tag_with_ref: true
          add_git_labels: true
          push: true
